spring:
  rabbitmq:
    host: 192.168.100.189  # rabbitMQ server IP
    port: 5672       # rabbitMQ server port
    username: anan
    password: 123456

server:
  port: 8091
  servlet:
    context-path: /consumer

## rabbitMQ properties ,the name as you like
mq:
  config:
    exchange: order.fanout  # 交换器的名称
    queue:
      sms: # 短信队列名称
        value: order.sms  # 服务名称
      push: # push 队列名称
        value: order.push

